// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wireDemo/wireStruct"
)

// Injectors from wire.go:

// 注入
func NewWire() wireStruct.FooBar {
	foo := wireStruct.NewFoo()
	bar := wireStruct.NewBar()
	fooBar := wireStruct.FooBar{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBar
}

func NewWireTwo() wireStruct.FooBar {
	foo := wireStruct.NewFoo()
	fooBar := wireStruct.FooBar{
		MyFoo: foo,
	}
	return fooBar
}
