// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wireDemo/wireValue"
)

// Injectors from wire.go:

// 注入方式1：通过set
func NewWire() wireValue.Foo {
	foo := _wireFooValue
	return foo
}

var (
	_wireFooValue = wireValue.Foo{X: 2024}
)

// 注入方式2：直接注入value
func NewWireTwo() wireValue.Foo {
	foo := _wireWireValueFooValue
	return foo
}

var (
	_wireWireValueFooValue = wireValue.Foo{X: 2025}
)
