// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wireDemo/wireCleanUp"
)

// Injectors from wire.go:

func NewWire() (string, func(), error) {
	string2, cleanup, err := wireCleanUp.NewFile()
	if err != nil {
		return "", nil, err
	}
	return string2, func() {
		cleanup()
	}, nil
}
