# riscv
riscv_build:
	GOOS=linux GOARCH=riscv64 go build main.go

# 龙芯
loongarch_build:
	GOOS=linux GOARCH=loong64 go build main.go


# .NET 芯片的支持
# https://github.com/dotnet/runtime/tree/main/src/coreclr/vm