// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"wireDemo/wireBaseDemo"
)

// Injectors from wire.go:

// 注入
func NewWire(ctx context.Context) (wireBaseDemo.Baz, error) {
	foo := wireBaseDemo.NewFoo()
	bar := wireBaseDemo.NewBar(foo)
	baz, err := wireBaseDemo.NewBaz(ctx, bar)
	if err != nil {
		return wireBaseDemo.Baz{}, err
	}
	return baz, nil
}

func NewWireSet(ctx context.Context) (wireBaseDemo.Baz, error) {
	foo := wireBaseDemo.NewFoo()
	bar := wireBaseDemo.NewBar(foo)
	baz, err := wireBaseDemo.NewBaz(ctx, bar)
	if err != nil {
		return wireBaseDemo.Baz{}, err
	}
	return baz, nil
}
