// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"wireDemo/wireBaseDemo"
)

// Injectors from wire.go:

// 直接依赖 供给者的 注入方式
func NewWire(ctx context.Context) (wireBaseDemo.Baz, error) {
	foo := wireBaseDemo.NewFoo()
	bar := wireBaseDemo.NewBar(foo)
	baz, err := wireBaseDemo.NewBaz(ctx, bar)
	if err != nil {
		return wireBaseDemo.Baz{}, err
	}
	return baz, nil
}

// 依赖 供给者集合的 注入方式
func NewWireSet(ctx context.Context) (wireBaseDemo.Baz, error) {
	foo := wireBaseDemo.NewFoo()
	bar := wireBaseDemo.NewBar(foo)
	baz, err := wireBaseDemo.NewBaz(ctx, bar)
	if err != nil {
		return wireBaseDemo.Baz{}, err
	}
	return baz, nil
}

func NewWireSet2(ctx context.Context) (wireBaseDemo.Baz, error) {
	foo := _wireFooValue
	bar := wireBaseDemo.NewBar(foo)
	baz, err := wireBaseDemo.NewBaz(ctx, bar)
	if err != nil {
		return wireBaseDemo.Baz{}, err
	}
	return baz, nil
}

var (
	_wireFooValue = wireBaseDemo.Foo{X: 2025}
)
